user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"

default_headers:
  Accept: "application/json, text/javascript, */*; q=0.01"
  Accept-Language: "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"
  Connection: "keep-alive"
  Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"
  Host: "veiculos.fipe.org.br"
  Origin: "https://veiculos.fipe.org.br"
  Referer: "https://veiculos.fipe.org.br/"
  X-Requested-With: "XMLHttpRequest"

api_endpoints:
  tabelas: "https://veiculos.fipe.org.br/api/veiculos/ConsultarTabelaDeReferencia"
  marcas: "https://veiculos.fipe.org.br/api/veiculos/ConsultarMarcas"
  modelos: "https://veiculos.fipe.org.br/api/veiculos/ConsultarModelos"
  ano_modelos: "https://veiculos.fipe.org.br/api/veiculos/ConsultarAnoModelo"
  veiculo: "https://veiculos.fipe.org.br/api/veiculos/ConsultarValorComTodosParametros"

vehicle_types:
  1: "carro"
  2: "moto"
  3: "caminhao"

fuel_types:
  '1': "Gasolina"
  '2': "Álcool"
  '3': "Diesel"
  '4': "Flex"

month_mapping:
  janeiro: "01"
  fevereiro: "02"
  março: "03"
  abril: "04"
  maio: "05"
  junho: "06"
  julho: "07"
  agosto: "08"
  setembro: "09"
  outubro: "10"
  novembro: "11"
  dezembro: "12"

rate_limit_capacity: 5
rate_limit_refill: 1
timeout: 20
max_workers: 5